#!/bin/bash

HAS_NETWORK=0

shopt -s nullglob

function cleanup {
    for arg; do
        if [ -f "$arg" ]; then
            rm $arg
        fi
    done
}

function error {
    status "ERROR"
    echo "$@" | tee ERROR
    exit 1
}

function status {
    echo "$@" | tee STATUS
}

function connect {
    netctl stop-all
    status "Connecting to $1"
    netctl start "$1"
    if [ "$?" -eq "0" ]; then
        HAS_NETWORK=1
        status "Connected to $1"
    else
        HAS_NETWORK=0
        status "Failed to connect to $1"
    fi
    return $HAS_NETWORK
}

function sync_time {
    ntp-wait -n 5
    if [ "$?" -ne "0" ]; then
        error "NTP time sync failed."
    fi
    hwclock -w
}

cleanup "ERROR"

if [ ! -e "/sys/class/net/wlan0" ]; then
    error "Missing WiFi interface"
fi

[ -d /sys/class/i2c-adapter/i2c-1/1-0068/ ] && echo 0x68 > /sys/class/i2c-adapter/i2c-1/delete_device
echo ds3231 0x68 > /sys/class/i2c-adapter/i2c-1/new_device

if [ "$?" -ne "0" ]; then
    error "RTC hardware error"
fi

if [ -f "PROFILE" ]; then
    connect `cat PROFILE`
fi

if [ "$HAS_NETWORK" -eq "1" ]; then
    sync_time
else
    hwclock -s
    systemctl start create_ap    
fi

if [ "`date +%Y`" -lt "2010" ]; then
    status "Date incorrect"
fi
